services:
  - type: web
    name: fraud-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run realtime_dashboard.py --server.port 10000
    repo: https://github.com/Akeel3105/fraud-dashboard-streamlit
    branch: main
    autoDeploy: true

