services:
  - type: web
    name: fraud-api
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    repo: https://github.com/Akeel3105/fraud-dashboard-streamlit
    branch: main
    autoDeploy: true
